/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package n.coroutines

import kotlinx.coroutines.*
import kotlin.system.measureTimeMillis

class Library {
    companion object {

        @JvmStatic
        fun main(args: Array<String>) {
            var counter = 0
            val numberOfCoroutines = 1_000_000L

            val sc = CoroutineScope(Dispatchers.Default)
            val time = measureTimeMillis {
                for(i in 1..numberOfCoroutines) {
                    launch {
                        counter += 1
                    }
                }
            }
        }
    }
    fun someLibraryMethod(): Boolean {
        return true
    }
}
